### ISSUE TITLE
Won't launch in modpack

### ISSUE THREAD

**Issue by EagleStrike118** [BuiltBrokenModding/MFFS_Classic#21]
Hello! I can get MFFS and Voltz Engine to run in "normal" Minecraft, using 1.7.10 Forge. However, whenever I put it in a modpack, and upload it to technic, it doesn't work. I first thought that it was conflicting with other mods, so I put MFFS and Voltz (along with the CodingLib download) in there own modpack. The modpack downloads fine, however whenever I launch it, it will get to 19-25%, speed up to 100%, go to the black "transition" screen then "crash." However, there aren't any crash files. Any idea as to why this is happening?

Love the mod btw, works extremely well with forge.

**Comment by DarkGuardsman** [comment]
Any chance you can upload the crash to [pastebin](http://pastebin.com/) (or a similar site) and post the link here. That way I can see why it is crashing.

**Comment by EagleStrike118** [comment]
[dEUGQdw2.txt](https://github.com/BuiltBrokenModding/MFFS_Classic/files/836309/dEUGQdw2.txt)

**Comment by DarkGuardsman** [comment]
`java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker` is part of forge. Have you confirmed the game will load without any mods?

**Comment by EagleStrike118** [comment]
Technic will launch other modpacks just fine, if that is what you mean. Also, I believe that was the full log. In the "logs" folder in my ".technic," that was the only file, and it only has the 14-or-so lines.

**Comment by DarkGuardsman** [comment]
Normally when creating a technic modpack you provide a mod.jar that contains forge. If your pack has done this you might want to test that the pack loads with no mods (not other packs in the launcher). As the forge install itself could be bad causing an error along the lines of the one in the log. Especially since the log file is so small and contains nothing pointing at VoltzEngine to indicate a direct error in the mod. 

Normally when VoltzEngine or MFFS fails you will get a crash with FML or Forge saying "Mod has crashed during phase" with an error multi lines long. If CodingLibs fails the crash would be from inside VoltzEngine with the same error but a long list of error lines.

**Comment by EagleStrike118** [comment]
Okay thank you, I will try that now.

**Comment by EagleStrike118** [comment]
I was able to get it to work in the modpack. Thanks for the help! However, the game crashes whenever the forcefield extends past 44 "size upgrades", or about 80ish blocks. Is this just because of the load on the game, or is something wrong with the specific version I downloaded?
[rXdcC32r.txt](https://github.com/BuiltBrokenModding/MFFS_Classic/files/836397/rXdcC32r.txt)

**Comment by DarkGuardsman** [comment]
Its a known issue that is being worked on slowly https://github.com/BuiltBrokenModding/MFFS_Classic/issues/13
